pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3033:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                script {
                    input(message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed', submitter: 'user1,user2')
                }
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the website? (Click "Proceed" to continue)'
                echo 'Application is running. It will be available for 1 minute before shutting down.'
                sleep(time: 1, unit: 'MINUTES')
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
